anoopsalesforce/src/objects/TODO_Project__c.object
<CustomObject>
    <label>TODO Project</label>
    <nameField>
        <displayFormat>TODOPROJ-{000000}</displayFormat>
        <label>TODO Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TODO Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

anoopsalesforce/src/objects/TODO_Task__c.object
<CustomObject>
    <fields>
        <fullName>TODO_Project__c</fullName>
        <label>TODO Project</label>
        <referenceTo>TODO_Project__c</referenceTo>
        <relationshipLabel>TODO Tasks</relationshipLabel>
        <relationshipName>TODO_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TODO Task</label>
    <nameField>
        <displayFormat>TODOTASK-{000000}</displayFormat>
        <label>TODO Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TODO Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

anoopsalesforce/src/classes/TODO_Application.cls
public with sharing class TODO_Application {

	public static final fflib_Application.UnitOfWorkFactory unitOfWork =
		new fflib_Application.UnitOfWorkFactory(
			new List<SObjectType>{
				TODO_Project__c.SObjectType,
				TODO_Task__c.SObjectType
			}
		);

	public static final fflib_Application.ServiceFactory service = 
		new fflib_Application.ServiceFactory(
			new Map<Type, Type>{
				TODO_ProjectsService.IService.class => TODO_ProjectsService.class
			}
		);

	public static final fflib_Application.SelectorFactory selector =
		new fflib_Application.SelectorFactory(
			new Map<SObjectType, Type>{
				TODO_Project__c.SObjectType => TODO_ProjectsSelector.class
			}
		);

	public static final fflib_Application.DomainFactory domain = 
		new fflib_Application.DomainFactory(
			TODO_Application.Selector,
			new Map<SObjectType, Type> {
				
			}
		);

}