anoopsalesforce/src/objects/TODO_Project__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>TODO Project</label>
    <nameField>
        <displayFormat>TODOPROJ-{000000}</displayFormat>
        <label>TODO Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TODO Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

anoopsalesforce/src/classes/TODO_Projects.cls
public with sharing class TODO_Projects extends fflib_SObjectDomain 
											implements IDomain {
	
	public interface IDomain {
		void deactivateProjects();
		void activateProjects();
	}


	public static IDomain newInstance(List<TODO_Project__c> sObjectList){
		return (IDomain)
			TODO_Application.domain.newInstance(sObjectList);
	}

	public TODO_Projects(List<TODO_Project__c> records){
		super(records);
	}

	public override void onApplyDefaults(){
		for(TODO_Project__c project : (List<TODO_Project__c>) records){
			project.Active__c = true;
		}
	}


	public override void onValidate(){
		validateDescription();
	}

	public override void onValidate(Map<Id, SObject> existingRecords){
		validateDescription();
	}

	private void validateDescription(){
		for(TODO_Project__c project : (List<TODO_Project__c>) records){
			if(String.isBlank(project.Description__c)){
				project.Description__c.addError(
					error( 
						'You need to enter a description', 
							project,  
								TODO_Project__c.Description__c)
				);
			}
		}
	}


	public void deactivateProjects(){
		for(TODO_Project__c project : (List<TODO_Project__c>) records){
			project.Active__c = false;
		}
	}

	public void activateProjects(){
		for(TODO_Project__c project : (List<TODO_Project__c>) records){
			project.Active__c = true;
		}
	}



	public class Constructor implements fflib_SObjectDomain.IConstructable {
		public fflib_SObjectDomain construct(List<SObject> sObjectList){
			return new TODO_Projects(sObjectList);
		}
	}
}