anoopsalesforce/src/objects/TODO_Project__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>TODO Project</label>
    <nameField>
        <displayFormat>TODOPROJ-{000000}</displayFormat>
        <label>TODO Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TODO Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

anoopsalesforce/src/classes/TODO_ProjectsSelector.cls
public class TODO_ProjectsSelector extends fflib_SObjectSelector 
											implements ISelector {

	public interface ISelector extends fflib_ISObjectSelector {
		List<TODO_Project__c> selectById(Set<Id> recordIds);
	}


	public static ISelector newInstance(){
		return (ISelector) 
			TODO_Application.selector.newInstance(TODO_Project__c.sObjectType);
	}


	public List<Schema.SObjectField> getSObjectFieldList(){
		return new List<Schema.SObjectField>{
			TODO_Project__c.Id,
			TODO_Project__c.Description__c,
			TODO_Project__c.Active__c
		};
	}


	public Schema.SObjectType getSObjectType(){
		return TODO_Project__c.SObjectType;
	}

	public List<TODO_Project__c> selectById(Set<Id> recordIds){
		return (List<TODO_Project__c>) selectSObjectsById(recordIds);
	}

}